### ISSUE TITLE
[error help] The compilation of the microxrcedds_client software package fails

### ISSUE THREAD

**Issue by kurisaW** [micro-ROS/micro_ros_rtthread_component#2]
A while ago, I was testing on the ARM Cortex-M4 and M7 platforms and had specified the relevant toolchain configuration in the toolchain.cmake script. However, after compilation, it consistently got stuck at the microxrcedds_client software package. Below is a compilation screenshot:

![image](https://github.com/micro-ROS/micro_ros_rtthread_component/assets/98592772/3ce2f06f-6351-46a3-88c8-83b959b4affc)

I even attempted to compile overnight, but it still got stuck at the compilation of the microxrcedds_client software package. So, in accordance with the Tricore platform supported by the repository README, I installed Infineon's toolchain and tried to compile again. However, I still encountered the same issue, where it got stuck at the compilation of the microxrcedds_client software package. 

I wanted to ask if you have any insights or suggestions regarding this situation. Any guidance you can provide would be greatly appreciated! @pablogs9 @Acuadros95

**Comment by pablogs9** [comment]
`microxrcedds_client` is a lightweight package and it shall not take too long to compile. In order to understand further the situation I would like to:

- Check with `htop` what is happening with your CPU and RAM while building?
- Add verbosity to colcon build [here](https://github.com/micro-ROS/micro_ros_rtthread_component/blob/051828e8da57b11825df7050056cb02b3f5c5c26/builder/microros_utils/library_builder.py#L89) with this approach: https://colcon.readthedocs.io/en/released/user/how-to.html#show-all-output-immediately-on-the-console
- Know if you have tried to build with a normal, ubuntu-distributed GCC ARM compiler
- What did you change with respect to https://github.com/micro-ROS/micro_ros_rtthread_component/issues/1, because there the compilation was successful
